# @package _global_
# configs/eval/math/math_AIME24.yaml апстрима с concurrency: 1
defaults:
  - /agents/practice/math_agent@agent
  - _self_

exp_id: "math_AIME24_eval"

data:
  dataset: "AIME24"

concurrency: 1
pass_k: 32

verify_filename: "math.py"
verify_func_name: "verify_func"
